TK_D12/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('tinymce', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('schedule/', include('Schedule.urls')),
    path('doctor/', include('doctor.urls', namespace='doctor')),
    path('article/', include('article.urls', namespace='article')),
	path('', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path
from . import views

app_name = 'doctor'

urlpatterns = [
	path('', views.ListDoctor, name="listdoctor"),
	path('<int:id>', views.DetailDoctor),
	path('addcomment', views.AddComment, name="addComment"),
	path('commentList/<int:id>', views.MyJsonFunction, name="getCommentList"),
	path('like/<int:id>', views.LikeButton, name="LikeButton"),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('covid_cases/', views.covid_cases, name='covid_cases'),
    path('post_suggestion/', views.post_suggestion, name='post_suggestion'),
    path('process_suggestions/', views.process_suggestions, name='process_suggestions'),
    path('suggestions/', views.list_of_suggestions, name='suggestions'),
]

doctor/models.py
from django.db import models
from django.conf import settings

class Doctor(models.Model):
	profile_picture = models.ImageField(upload_to='Profile_Picture/', default='default.jpg')
	name = models.CharField(max_length=50)
	degree_name = models.CharField(max_length=80)
	message = models.TextField()
	known_for = models.TextField()
	path_to = models.TextField()
	passion = models.TextField()
	fav_quote = models.TextField()
	fav_quote_by = models.CharField(max_length=50)
	like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="doctor_profile") #user-likes-doctor

	def jumlah_total_like(self):
		return self.like.count()

class Comment(models.Model):
	username = models.CharField(max_length=60)
	text = models.TextField(blank = False, default="")
	doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE) #Many to one

doctor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Doctor, Comment
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse

def DetailDoctor(request, id):
	doctor = Doctor.objects.get(id = id)
	context = {
		"data": doctor,
	}
	return render(request, 'doctor/detailDoctor.html', context)

def AddComment(request):
	if request.user.is_authenticated:
		id = request.POST.get('doctorID', None)
		doctor = Doctor.objects.get(id = id)
		comment = request.POST.get('comment', None)
		if (str(comment) != str("")):
			Comment.objects.create(username = request.user.username, doctor = doctor, text = comment)
		return redirect('/doctor/' + id)
	else:
		messages.error(request, "You have to log in first to post a comment.")			
		return redirect('/login')

def MyJsonFunction(request, id):
	doctor = Doctor.objects.get(id = id)
	queryset = Comment.objects.filter(doctor = doctor)
	
	dict = {}
	num = 1
	for comments in queryset:
		dict[num] = [comments.username, comments. text]
		num = num + 1
	
	return JsonResponse(dict)
	

def ListDoctor(request, **kwargs):
	doctors = Doctor.objects.all()
	doctorsList = []
	for i in doctors:
		doctorsList.append(i)
	context = {'doctorsList': doctorsList} 
	return render(request, 'doctor/listDoctor.html', context)

def LikeButton(request, id):
	if request.user.is_authenticated:
		doctor_like = Doctor.objects.get(id=id)
		doctor_like.like.add(request.user)
		return redirect('/doctor/')
	else:
		messages.error(request, "You have to log in first to post a comment.")			
		return redirect('/login')

doctor/templates/doctor/detailDoctor.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}<title>Our Doctors - {{ data.name }}</title>{% endblock title%}

{% block style %}
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-2.1.3.min.js" integrity="sha256-ivk71nXhz9nsyFDoYoGf2sbjrR9ddh+XDkCcfZxjvcM=" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"/>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
	<script type = "text/javascript">
		$(document).ready(function() { 
			var jsonUrl = "/doctor/commentList/{{ data.id }}";
			var data = $.ajax({
				url: jsonUrl,
				async: false,
				dataType: 'json'
			}).responseJSON;
			
			// counting how much data there is
			var dataCount = 0;
			for (i in data) {
				dataCount += 1;
			}
			
			// variable 'num' is used as a pointer
			if (dataCount == 0) {
				var num = 0;
				$('#more-comment').empty();
				$('#list-comment').append("<h3 style=\"text-align:center\">There is no comment yet, post a comment!</h3>");
			}
			else {
				var num = 1;
			}
			
			// do showComment first
			showComment();
			
			// add event listener to #show-more-comment
			// add hover to #show-more-comment too
			var commentListener = document.getElementById("show-more-comment");
			commentListener.addEventListener("click", function() {
				showComment();
			});
			$("#show-more-comment").hover(function(){
				$(this).css("color", "blue");
			}, function(){
				$(this).css("color", "black");
			});
			
			// add function to show more comment
			function showComment() {
				console.log("getting more comments");
				var tempNum = num + 4;
				var username;
				var text;
				var temp;
				var i;
				if (num <= dataCount) {
					if (tempNum < dataCount) { // tambahkan 5 data saja dengan #show-more-comment
						for (i = num; i <= tempNum; i++) {
							username = data[i][0];
							text = data[i][1];
							temp = '\
									<div class="col-12">\
										<hr>\
										<h2>' + username + '</h2>\
										<h3>' + text + '</h3>\
										<hr>\
									</div>'	
							$('#list-comment').append(temp);
							num++;
						}
					} else { // tambahkan semua sisa data tanpa button
						for (i = num; i <= dataCount; i++) {
							username = data[i][0];
							text = data[i][1];
							temp = '\
									<div class="col-12">\
										<hr>\
										<h2>' + username + '</h2>\
										<h3>' + text + '</h3>\
										<hr>\
									</div>'
							$('#list-comment').append(temp);
							num++;
						}
						$('#more-comment').empty();
					}
				}
			}
		});
	</script>
	<style type = text/css>

        body, html {
			font-family: 'Lato', sans-serif;
		}
		.content {
			min-height: 100%;
			margin-top: 50px;
			margin-bottom: 50px;
		}
		h1 {
			text-align: center;
		}
		.introduction {
			max-width: 700px;
			text-align: center;
			position: relative;
		}
		.introduction img {
			width: 120px;
			height: 120px;
			border-radius: 50%;
			float: left;
		}
		.introduction h2 {
			font-weight: bold;
		}
		.introduction .lead {
			text-align: left;
			padding-left: 140px;
		}
		.common-data {
			margin-right: 250px;
			margin-left: 250px;
			text-align: left;
		}
		.common-data p {
			font-size: 20px;
		}
		.quotes {
			text-align: center;
			max-width: 800px;
			min-height:250px;
			text-align: center;
			position: float;
			border-style: groove;
			padding: 20px;
			margin-top: 30px;
			margin-bottom: 10px;
			margin-left: auto;
			margin-right: auto;
		}
		.quotes h2 {
			text-align: left;
			font-size: 30px;
		}
		.quotes h3 {
			text-align: center;
			font-size: 25px;
		}
		.quotes h4 {
			text-align: right;
		}
		#comment-box {
			text-align: center;
			width: 600px;
			min-height:50px;
			text-align: center;
			position: float;
			border-style: groove;
			padding: 7px;
			margin-top: 30px;
			margin-bottom: 10px;
			margin-left: auto;
			margin-right: auto;
		}
		button {
			height: 50px;
		}
		#list-comment {
			text-algin: left;
			margin-left: 200px;
			margin-right: 200px;
			padding: 20px;
		}
		#list-comment h2 {
			padding-left: 100px;
			padding-right: 100px;
			font-weight: bold;
			font-size: 30px;
		}
		#list-comment h3 {
			padding-left: 100px;
			padding-right: 100px;
		}
		@media only screen and (max-width:1200px) {
			.common-data {
				margin-right: 100px;
				margin-left: 100px;
			}
			#list-comment {
				text-algin: left;
				margin-left: 30px;
				margin-right: 30px;
				padding: 20px;
			}
			#list-comment h2 {
				padding-left: 10px;
				padding-right: 10px;
			}
			#list-comment h3 {
				padding-left: 10px;
				padding-right: 10px;
			}
		}
		@media only screen and (max-width:928px) {
			.common-data {
				margin-right: 30px;
				margin-left: 30px;
			}
			.quotes {
				margin-left: 30px;
				margin-right: 30px
			}
		}
		@media only screen and (max-width:768px) {
			#about h2 {
				margin-top: 20px;
				font-size: 30px;
			}
			.introduction img {
				height: 100px;
				width: 100px;
				float: none;
				display: inline-block;
			}
			.introduction h2 {
				margin-top: 10px;
				margin-bottom: 5px;
			}
			.introduction .lead {
				padding-left: 30px;
				padding-right: 30px;
				text-align: center;
			}
			.likes button {
				float: none;
				display: inline-block;
				margin-bottom: none;
			}
			.likes .lead {
				margin-top: none;
				padding-left: 30px;
				padding-right: 30px;
				text-align: center;
			}
		}
    </style>
<!script src="https://code.jquery.com/jquery-3.5.1.js"><!/script>
{% endblock style %}

{% block content %}

	<div class="content">
		<div class="col-12 d-flex justify-content-center">
          <div class="introduction">
            <img src="{{ data.profile_picture.url }}" alt="Profile Picture">
            <h2 class="lead">{{ data.name }}</h2>
            <p class="lead">{{ data.message }}</p>
          </div>
        </div>
		<br>
		<div class = "common-data">
			<div class="col-12 d-flex justify-content-center">
				<p><b>Known For:</b> {{ data.known_for }}</p>
			</div><br>
			<div class="col-12 d-flex justify-content-center">
				<p><b>Path to <i>GetHealthy</i>:</b> {{ data.path_to }}</p>
			</div><br>
			<div class="col-12 d-flex justify-content-center">
				<p><b>Passion:</b> {{ data.passion }}</p>
			</div><br>
		</div>
		<div class = "quotes">
			<h2><b>Favorite Quote:</b></h2><br>
			<h3><i>"{{ data.fav_quote }}"</i></h3><br>
			<h4>- {{ data.fav_quote_by }}</h4>
		</div>
		
		<br>
		<h1>Comments</h1>
		<div style="text-align:center">
			<form action="{% url 'doctor:addComment' %}" method="post">
				{% csrf_token %}
				<input name="doctorID" type="hidden" value="{{ data.id }}">
				<p>Post a comment!</p>
				<input id="comment-box" name="comment" style="text-align: left;" type="text" autofocus/>
				<button type="submit" class="btn btn-primary">Post</button>
			</form>
		</div>
		<section id="list-comment"></section>
		<div id="more-comment">
			<h3 style="text-align: center;"><a href="#show-more-comment" id="show-more-comment" style="color:black">Show more comments</a></h3>
		</div>
	</div>
{% endblock content %}

doctor/templates/doctor/listDoctor.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}<title>Our Doctors</title>{% endblock title%}

{% block content %}
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Our Doctor</title>
		<script src="https://code.jquery.com/jquery-2.1.3.min.js" integrity="sha256-ivk71nXhz9nsyFDoYoGf2sbjrR9ddh+XDkCcfZxjvcM=" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
		<link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
		<style type = text/css>

			header, body, html {
				font-family: 'Lato', sans-serif;
				margin: 0;
				padding: 0;
			} 

			h1 {
				font-size: 50px;
				text-align: center;
				color: #33726D;
				font-weight: bold;
			}

			h5,h4 {
				text-align: center;
				color: #33726D;
			}

			button {
				margin-right: auto;
				margin-left: auto;
				margin-top: 25px;
				margin-bottom: 25px;
				transform: scale(1.5);
				display: grid;
				color: #33726D;
				background: #FCF8F8;
				box-sizing: border-box;
				border: 1px solid #33726D;
				border-radius: 6px;
			}

			.card {
				margin: auto;
				margin-top: 40px;
				width: 300px;
				min-height: 400px;
			}

			.card-img-top {
				text-align: center;
				width: 300;
				height: 300;
				object-fit: cover;
			}

			.doctor-name {
				color: #154440;
				font-size: 25px;
				font-weight: bold;
				text-align: left;
				margin-top: 20px;
			}

			.doctor-name-degree {
				color: black;
				font-size:17px;
				text-align: left;
				margin-top: 0;
			}

			.doctor-name-like {
				color: black;
				font-size:17px;
				text-align: right;
				margin-top: 0;
			}
		</style>
	</head>

	<body>
		<!--Meet Doctors-->
		<br><br>
		<h1>Meet Our Doctors</h1>
		<h5>key staff of <i>GetHealty</i></h5>
		{% for i in doctorsList %}
			{% if forloop.first %}
				<div class = "row" style="margin-left: 100px; margin-right: 100px;">
			{% endif %}
					<div class="col-md-4">
						<div class="card border-0">
							<a href='/doctor/{{ i.id }}'>
								{% if i.profile_picture %}
									<img src="{{ i.profile_picture.url }}" class="card-img-top">
								{% endif %}
								<p class="card-text doctor-name">{{i.name}}</p>
							</a>
							<p class="card-text doctor-name-degree">{{i.degree_name}}</p>
							<p class="card-text doctor-name-like">Likes - {{ i.like.count }}</p>
							<form action="/doctor/like/{{i.id}}" method="POST">
								{% csrf_token %}
								<button type="submit" class="btn btn-primary btn-sm" value="{{ doctor.id }}" name="like_button_id">Like</button>
							</form>
						</div>
					</div>
					{% if forloop.counter|divisibleby:3 %}
				</div>
						<div class="row" style="margin-left: 100px; margin-right: 100px;">
					{% endif %}
							{% if forloop.last %}
						</div>
							{% endif %}
		{% endfor %}

		<!--Book Us-->
		<br><br>
		<h1>Book Us!</h1>
		<h4>With our service you can book our doctor to give you a private consultation via online.</h4>
		<a href="/schedule/"><button>Consultation</button></a>
		<br><br>
		{% endblock %}

	</body>
</html>