TK_D12/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('tinymce', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('schedule/', include('Schedule.urls')),
    path('doctor/', include('doctor.urls', namespace='doctor')),
    path('article/', include('article.urls', namespace='article')),
	path('', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'article'

urlpatterns = [
    path('', views.article, name='article'),
    path('news/<slug:slug>/', views.news, name='news'),
    path('tipsandtrick/<slug:slug>/', views.tipsandtrick, name='tipsandtrick'),
    path('search_news/', views.search_news, name="search_news"),
    path('search_tips/', views.search_tips, name="search_tips"),
    path('news_api/', views.get_news, name="get_news"),
    path('tips_api/', views.get_tips, name="get_tips"),
    path('json_news/', views.data_news, name="data_news"),
    path('json_tips/', views.data_tips, name="data_tips"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('covid_cases/', views.covid_cases, name='covid_cases'),
    path('post_suggestion/', views.post_suggestion, name='post_suggestion'),
    path('process_suggestions/', views.process_suggestions, name='process_suggestions'),
    path('suggestions/', views.list_of_suggestions, name='suggestions'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from autoslug import AutoSlugField
from tinymce import models as tinymce_models, HTMLField
from account.models import Account


# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=100, default="")
    slug = AutoSlugField(populate_from='title')
    date = models.DateField(auto_now_add=True)
    content = HTMLField('Content')
    image = models.ImageField(null=True, blank=True, upload_to='image')

    def slugify_function(self, content):
        return content.replace('_', '-').lower()

    def __str__(self):
        return self.title

class TipsAndTrick(models.Model):
    title = models.CharField(max_length=100, default="")
    slug = AutoSlugField(populate_from='title')
    date = models.DateField(auto_now_add=True)
    content = HTMLField('Content')
    image = models.ImageField(null=True, blank=True, upload_to='image')

    def __str__(self):
        return self.title
    
    def slugify_function(self, content):
        return content.replace('_', '-').lower()

class CommentsNews(models.Model):
    post = models.ForeignKey(News,on_delete=models.CASCADE,related_name='comments_news', default="", null=True)
    user = models.ForeignKey(Account, on_delete= models.CASCADE,related_name='news_posts', default="", null=True)
    comment = models.TextField()
    published = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['published']

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.user)

class CommentsTipsAndTrick(models.Model):
    post = models.ForeignKey(TipsAndTrick,on_delete=models.CASCADE,related_name='comments_tips_and_trick', default="", null=True)
    user = models.ForeignKey(Account, on_delete= models.CASCADE,related_name='tips_posts', default="", null=True)
    comment = models.TextField()
    published = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['published']

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.user)

article/forms.py
from .models import CommentsNews, CommentsTipsAndTrick
from django import forms

class CommentNewsForm(forms.ModelForm):
    class Meta:
        model = CommentsNews
        fields = ('comment',)


class CommentTipsAndTrickForm(forms.ModelForm):
    class Meta:
        model = CommentsTipsAndTrick
        fields = ('comment',)

article/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from .models import News, TipsAndTrick, CommentsNews, CommentsTipsAndTrick
from .forms import CommentNewsForm, CommentTipsAndTrickForm
from django.core import serializers
from .serializers import NewsSerializer, TipsAndTrickSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response
import json
import requests


# Create your views here.
def article(request):
    news = News.objects.all()
    tips = TipsAndTrick.objects.all()
    context = {
        "news": news,
        "tips": tips
    }
    return render(request, "article.html", context)


def news(request, slug):
    post = get_object_or_404(News, slug=slug)
    post_id = post.id

    user = request.user
    user_id = user.id

    if request.method == 'POST':
        comment_form = CommentNewsForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.post_id = post_id
            comment_form.instance.user_id = user_id
            comment_form.save()
            comment_form = CommentNewsForm()
    else:
        comment_form = CommentNewsForm()

    comments = post.comments_news.filter(active=True)

    context = {
        'post': post,
        'comment_form': comment_form,
        'comments': comments,
        'user': user,
    }
    return render(request, 'news.html', context)


def tipsandtrick(request, slug):
    post = get_object_or_404(TipsAndTrick, slug=slug)
    user = request.user

    if request.method == 'POST':
        comment_form = CommentTipsAndTrickForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.save()
            comment_form = CommentTipsAndTrickForm()
    else:
        comment_form = CommentTipsAndTrickForm()

    comments = post.comments_tips_and_trick.filter(active=True)

    context = {
        'post': post,
        'comment_form': comment_form,
        'comments': comments,
        'user': user,
    }
    return render(request, 'tipsandtrick.html', context)

def search_news(request):
    context = {}
    return render(request, "search_news.html", context)

def search_tips(request):
    context = {}
    return render(request, "search_tips.html", context)

@api_view(['GET'])
def get_news(request):
    if request.method == "GET":
        news = News.objects.all()
        serializer = NewsSerializer(news, many=True)
        return Response(serializer.data)

@api_view(['GET'])
def get_tips(request):
    if request.method == "GET":
        tips = TipsAndTrick.objects.all()
        serializer = TipsAndTrickSerializer(tips, many=True)
        return Response(serializer.data)

def data_news(request):
    query = request.GET.get('q', None)
    absolute_url = request.build_absolute_uri('/article/news_api/')
    ret = requests.get(absolute_url)
    data_news = json.loads(ret.content)
    output_news = [x for x in data_news if query in x['title'].lower()]
    return JsonResponse(output_news, safe=False)

def data_tips(request):
    query = request.GET.get('q', None)
    absolute_url = request.build_absolute_uri('/article/tips_api/')
    ret = requests.get(absolute_url)
    data_tips = json.loads(ret.content)
    output_tips = [x for x in data_tips if query in x['title'].lower()]
    return JsonResponse(output_tips, safe=False)

article/templates/article.html
{% extends 'home/base.html' %}
{% load static %}

<head>
    {% block css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">

    <!-- Font Google -->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">

    <!-- Bootstrap Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <title>Article</title>

    <style>
        .news-image,
        .tips-image {
            width: 70%;
        }

        .news-title,
        .tips-title {
            padding-top: 1rem;
        }

        #news,
        #tipsandtrick {
            padding: 7% 15%;
        }

        .news-box,
        .tips-box {
            text-align: center;
            font-family: "Lato", sans-serif;
            font-weight: bold;
            padding: 5%;
        }
    </style>
    {% endblock css %}

</head>

<body>

    {% block content %}
    <section id="news">

        <h2>NEWS   |   </h2>
        <a href="{% url 'article:search_news' %}"><h2>Search News</h2></a>

        <div class="row">
            {% for item in news %}
            <div class="news-box col-lg-6">
                {% if item.image %}
                <img class="news-image" src="{{item.image.url}}" alt="{{item.title}}">
                {% endif %}
                <a href="{% url 'article:news' slug=item.slug %}">
                    <h6 class="news-title">{{item.title}}</h6>
                </a>
            </div>
            {% endfor %}
        </div>

    </section>

    <section id="tipsandtrick">
        <h2>TIPS AND TRICK   |   </h2>
        <a href="{% url 'article:search_tips' %}"><h2>Search Tips</h2></a>

        <div class="row">
            {% for item in tips %}
            <div class="tips-box col-lg-6">
                {% if item.image %}
                <img class="tips-image" src="{{item.image.url}}" alt="{{item.title}}">
                {% endif %}
                <a href="{% url 'article:tipsandtrick' slug=item.slug %}">
                    <h6 class="tips-title">{{item.title}}</h6>
                </a>
            </div>
            {% endfor %}
        </div>

    </section>

    <script src="{% static 'article.js' %}"></script>
    {% endblock content %}

</body>

</html>

article/templates/news.html
{% extends 'home/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">

    <!-- Bootstrap Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <title>{{post.title}}</title>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');

        #detail {
            padding: 7% 15%;

        }

        .detail-title {
            text-align: center;
            color: #154440;
        }

        .detail-image {
            width: 50%;
            display: block;
            margin-top: auto;
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }

        .content,
        .detail-title {
            font-family: "Lato", sans-serif;
        }

        .detail-title,
        .detail-date {
            font-weight: bold;
        }

        .content {
            font-size: larger;
            text-align: justify;
            color: black;
        }
    </style>
    {% endblock css %}



</head>

<body>
    {% block content %}
    <script>
        $(document).ready(function() {
            $(".detail-title").hover(function(){
                        $(this).css("color", "aqua");
                    }, function() {
                        $(this).css("color", "#154440");
            });
        });
    </script>


    <section id="detail">
        {% if post.image %}
        <img src='{{post.image.url}}' class="detail-image" alt="{{post.title}}">
        {% endif %}
        <br>
        <h1 class="detail-title">{{post.title}}</h1>
        <br>
        <h6 class="detail-date">{{post.date}}</h6>
        <br>
        <div class="content">
            {% autoescape off %}
            {{post.content | safe}}
            {% endautoescape %}
        </div>


        {% if user.is_authenticated %}
            <h3>Leave a Comment</h3>

            {% load crispy_forms_tags %}

            <form method="post" action="">
                <fieldset>
                    {% csrf_token %}
                    {{ comment_form | crispy}}

                    <br>
                    <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
                </fieldset>
            </form>
            <br>
            
        {% else %}
        <h4>You are not logged in.</h4><br>
        <h5>Log in <a href="/login/">here.</a></h5>
        <br>

        {% endif %}

        <h3>{{comments.count}} Comments</h3>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
            <p class="font-weight-bold">
                {{ comment.user.username }}
                <span class=" text-muted font-weight-normal">
                    {{ comment.published }}
                </span>
            </p>
            {{ comment.comment | linebreaks }}
        </div>
        {% endfor %}


    </section>

    {% endblock content %}
</body>

</html>

article/templates/search_news.html
{% extends 'home/base.html' %}
{% load static %}

<head>
    {% block css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">

    <!-- Font Google -->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">

    <!-- Bootstrap Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/9ba1fbf095.js" crossorigin="anonymous"></script>

    <title>Search News</title>

    <style>
        .news-image,
        .tips-image {
            width: 70%;
        }

        .news-title,
        .tips-title {
            padding-top: 1rem;
        }

        #news,
        #tipsandtrick {
            padding: 7% 15%;
        }

        .news-box,
        .tips-box {
            text-align: center;
            font-family: "Lato", sans-serif;
            font-weight: bold;
            padding: 5%;
        }
    </style>
    {% endblock css %}
</head>

<body>

    {% block content %}
    <script>
        $(document).ready(function () {
            $("#keyword").keyup(function () {
                var input = $("#keyword").val();
                input = input.toLowerCase();

                $.ajax({
                    url: '/article/json_news?q=' + input,
                    success: function (output_news) {
                        $(".news-box").empty();
                        for (i = 0; i < output_news.length; i++) {
                            var news_article = output_news[i];

                            var title = news_article.title;
                            var image = news_article.image;
                            var slug = news_article.slug;
                            
                            $(".news-box").append(
                                "<img class='news-image' src=" + image + " alt=" + title + ">" + "<a href=\"/article/news/" + slug + "\"> <h6 class='news-title'>" + title + "</h6> </a>"
                            );
                        }
                    }
                });

                
            });
        })
    </script>

    <section id="news">
        <i class="fas fa-search" aria-hidden="true"></i>
        <input id="keyword" class="form-control form-control-sm ml-3 w-75" type="text" placeholder="Search news"
            aria-label="Search">
        <br>

        <div class="row">
            <div class="news-box col-lg-6">

            </div>
        </div>

        {% endblock content %}

</body>

</html>

article/templates/search_tips.html
{% extends 'home/base.html' %}
{% load static %}

<head>
    {% block css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">

    <!-- Font Google -->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">

    <!-- Bootstrap Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/9ba1fbf095.js" crossorigin="anonymous"></script>

    <title>Search News</title>

    <style>
        .news-image,
        .tips-image {
            width: 70%;
        }

        .news-title,
        .tips-title {
            padding-top: 1rem;
        }

        #news,
        #tipsandtrick {
            padding: 7% 15%;
        }

        .news-box,
        .tips-box {
            text-align: center;
            font-family: "Lato", sans-serif;
            font-weight: bold;
            padding: 5%;
        }
    </style>
    {% endblock css %}
</head>

<body>

    {% block content %}
    <script>
        $(document).ready(function () {
            $("#keyword").keyup(function () {
                var input = $("#keyword").val();
                input = input.toLowerCase();

                $.ajax({
                    url: '/article/json_tips?q=' + input,
                    success: function (output_tips) {
                        $(".tips-box").empty();
                        for (i = 0; i < output_tips.length; i++) {
                            var tips_article = output_tips[i];

                            var title = tips_article.title;
                            var image = tips_article.image;
                            var slug = tips_article.slug;
                            
                            $(".tips-box").append(
                                "<img class='tips-image' src=" + image + " alt=" + title + ">" + "<a href=\"/article/tipsandtrick/" + slug + "\"> <h6 class='tips-title'>" + title + "</h6> </a>"
                            );
                        }
                    }
                });
            });
        })
    </script>

<section id="tipsandtrick">
    <i class="fas fa-search" aria-hidden="true"></i>
    <input id="keyword" class="form-control form-control-sm ml-3 w-75" type="text" placeholder="Search Tips And Trick"
        aria-label="Search">
    <br>

    <div class="row">
        <div class="tips-box col-lg-6">

        </div>
    </div>
    
    {% endblock content %}

</body>

</html>

article/templates/tipsandtrick.html
{% extends 'home/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">

    <!-- Bootstrap Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <title>{{post.title}}</title>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');

        #detail {
            padding: 7% 15%;

        }

        .detail-title {
            text-align: center;
            color: #154440;
        }

        .detail-image {
            width: 50%;
            display: block;
            margin-top: auto;
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }

        .content,
        .detail-title {
            font-family: "Lato", sans-serif;
        }

        .detail-title,
        .detail-date {
            font-weight: bold;
        }

        .content {
            font-size: larger;
            text-align: justify;
            color: black;
        }
    </style>

    {% endblock css %}



</head>

<body>



    {% block content %}
    <script>
        $(document).ready(function() {
            $(".detail-title").hover(function(){
                        $(this).css("color", "aqua");
                    }, function() {
                        $(this).css("color", "#154440");
            });
        });
    </script>
    
    <div id="detail">
        {% if post.image %}
        <img src='{{post.image.url}}' class="detail-image" alt="{{post.title}}">
        {% endif %}
        <br> <br>
        <h1 class="detail-title">{{post.title}}</h1>
        <br>
        <h6 class="detail-date">{{post.date}}</h6>
        <br>
        <div class="content">
            {% autoescape off %}
            {{post.content | safe}}
            {% endautoescape %}
        </div>


        {% if user.is_authenticated %}
            <h3>Leave a Comment</h3>

            {% load crispy_forms_tags %}

            <form method="post" action="">
                <fieldset>
                    {% csrf_token %}
                    {{ comment_form | crispy}}

                    <br>
                    <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
                </fieldset>
            </form>
            <br>
            
        {% else %}
        <h4>You are not logged in.</h4><br>
        <h5>Log in <a href="/login/">here.</a></h5>

        {% endif %}

        <h3>{{comments.count}} Comments</h3>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
            <p class="font-weight-bold">
                {{ comment.user }}
                <span class=" text-muted font-weight-normal">
                    {{ comment.published }}
                </span>
            </p>
            {{ comment.comment | linebreaks }}
        </div>
        {% endfor %}

    </div>
    {% endblock content %}
</body>

</html>